// Generated by CoffeeScript 1.4.0

(function() {
  var s;
  s = document.createElement('script');
  s.setAttribute('src', '//cdnjs.cloudflare.com/ajax/libs/yepnope/1.5.4/yepnope.min.js');
  s.onload = function() {
    return yepnope({
      load: ['//cdnjs.cloudflare.com/ajax/libs/jquery/1.8.3/jquery.min.js', '//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.4.3/underscore-min.js', '//raw.github.com/joscha/eventr/master/lib/Eventr.js', '//raw.github.com/joscha/gmailui/master/lib/GMailUI.js', '//raw.github.com/joscha/gmailui/master/lib/example/decorate.js'],
      complete: function() {
        var bar, buttonBar, composeButton;
        console.log("GMailUI and all dependencies have been loaded successfully, let's have some fun :-)");
        composeButton = ($("[gh='cm'][role='button']")).get(0);
        buttonBar = $("[gh='mtb'] > div > div");
        if (buttonBar.length > 0) {
          bar = decorateGMail(jQuery, _, composeButton);
          buttonBar.first().append(bar);
        } else {
          alert('Are you sure you are in the GMail webapp when clicking the bookmarklet?');
        }
      }
    });
  };
  document.getElementsByTagName('body')[0].appendChild(s);
})();
