// Generated by CoffeeScript 1.4.0
var decorateGMail;

decorateGMail = (function($, _, button) {
  var a, aBoxes, b, bar, c, composeButton, d, dialogButton, i, item, onChange, popup, popupButton, presetItem, presetMenu, x, _i, _j;
  bar = new GMailUI.ButtonBar;
  popup = new GMailUI.Popup;
  popupButton = bar.append(new GMailUI.ButtonBarPopupButton(popup, '', 'GMailUI'));
  popup.append(new GMailUI.PopupLabel('Checkboxes'));
  a = popup.append(new GMailUI.Section);
  aBoxes = {
    A: a.append(new GMailUI.PopupCheckbox('A title', true, 'A tooltip', '')),
    B: a.append(new GMailUI.PopupCheckbox('B', true, 'B tooltip', '')),
    C: a.append(new GMailUI.PopupCheckbox('C', false, '', 'A looooooong title that would make no sense as a tooltip, but very much here.'))
  };
  _.each(aBoxes, function(checkbox, propName) {
    checkbox.addOnChange(function(e, checked) {
      console.log("" + propName + " is checked: " + checked);
    });
  });
  b = popup.append(new GMailUI.Section);
  b.append(new GMailUI.Separator);
  b.append(new GMailUI.PopupLabel('Submenu selections'));
  for (i = _i = 1; _i <= 2; i = ++_i) {
    presetMenu = new GMailUI.PopupMenu(popup);
    presetItem = b.append(new GMailUI.PopupMenuItem(presetMenu, "Item " + i, '', '', true));
    for (x = _j = 1; _j <= 3; x = ++_j) {
      item = new GMailUI.PopupMenuItem(presetItem, "Item " + i + "." + x, '', '', false);
      onChange = function(i, x) {
        return function(e, checked) {
          console.log("" + i + "." + x + " was checked: " + checked);
        };
      };
      item.addOnChange(onChange(i, x), true);
      presetMenu.append(item);
    }
  }
  c = popup.append(new GMailUI.Section);
  c.append(new GMailUI.Separator);
  composeButton = c.append(new GMailUI.Button('Compose new mail'));
  composeButton.on('click', function() {
    popupButton.close();
    Eventr.simulate(button, 'mousedown');
    Eventr.simulate(button, 'mouseup');
  });
  dialogButton = c.append(new GMailUI.Button('Open modal dialog'));
  dialogButton.on('click', function() {
    var cancelButton, container, dialog, footer, okButton;
    popupButton.close();
    dialog = new GMailUI.ModalDialog('Cupkace ipsum');
    container = dialog.append(new GMailUI.ModalDialog.Container);
    footer = dialog.append(new GMailUI.ModalDialog.Footer);
    okButton = footer.append(new GMailUI.ModalDialog.Button('OK', 'This button has no action attached'));
    i = 0;
    okButton.on('click', function() {
      if (++i > 3) {
        alert("You are hard to convince, aren't you :-)");
      }
    });
    cancelButton = footer.append(new GMailUI.ModalDialog.Button('Cancel', "I don't like sweets", 'cancel'));
    cancelButton.on('click', dialog.close);
    container.append("<div style=\"text-align: justify;\">\n	<img src=\"//www.google.com/images/srpr/logo3w.png\" data-tooltip=\"The Google logo\" alt=\"Google logo\" align=\"right\" style=\"padding-left: 10px;\">\n	Soufflé sugar plum caramels. Fruitcake sweet roll caramels halvah gummies pastry candy canes. Cake macaroon powder jelly cake sweet roll jelly-o marzipan. Cotton candy jujubes gummies chocolate bar gingerbread lemon drops. Donut fruitcake macaroon wafer croissant. Croissant lemon drops danish macaroon. Gummies lemon drops halvah gingerbread cupcake cookie bonbon. Dragée wypas halvah\n</div>");
    dialog.open();
  });
  d = popup.append(new GMailUI.ErrorSection('And here is an error message!'));
  return bar.getElement();
});
